### ISSUE TITLE
docker ?

### ISSUE THREAD

**Issue by ignatandrei** [cosminpopescu14/math-operations-swagger#1]
Could you put into an docker and run  ? ( do not transform in jar, just want to edit )

**Comment by cosminpopescu14** [comment]
https://github.com/cosminpopescu14/math-operations-swagger/commit/fcd89b19f53f868a93f75d68822907f4bbdb8781

**Comment by ignatandrei** [comment]
Please make first  a docker that compiles the sources into JAR and then executes
( in the dockerfile you have ADD ${JAR_FILE} math-operations-0.0.1-SNAPSHOT.jar - that should be compiled by docker)

**Comment by cosminpopescu14** [comment]
https://github.com/cosminpopescu14/math-operations-swagger/commit/4e75eceb44ce86ef1b868c90ace117dc07c17b8a

**Comment by ignatandrei** [comment]
Now it works!
http://localhost:8080/swagger-ui/index.html
http://localhost:8080/v2/api-docs

**Comment by cosminpopescu14** [comment]
Glad!
